version: '3.9'

services:
  web:
    image: python:3.10-slim  # or node:18 for Node.js
    container_name: third_temple
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"  # Adjust ports as needed
    command: >
      sh -c "pip install -r requirements.txt &&
             python main.py"  # Replace with npm install && npm start
    environment:
      - ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
